change-template: "- #$NUMBER - $TITLE (@$AUTHOR)"
categories:
  - title: '⚠ Breaking Changes'
    label: 'breaking change'
  - title: '🚀 Features'
    labels:
      - 'feature'
      - 'enhancement'
  - title: '🐛 Bug Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
  - title: '🧰 Maintenance'
    labels:
      - 'maintenance'
      - 'dependencies'
      - 'documentation'
      - 'github_actions'
template: |
  ## What’s Changed

  $CHANGES